# Code Author Naveen Kumar Vadlamudi 
# Using DISTINCT + COUNT + WHERE Condition

CREATE FUNCTION getUserIDs(startDate DATE, endDate DATE, minAmount INT) RETURNS INT
BEGIN
  RETURN (
     SELECT COUNT(DISTINCT USER_ID)
     FROM PURCHASES 
     WHERE TIME_STAMP BETWEEN TIMESTAMP(STARTDATE) AND TIMESTAMP(ENDDATE)
     AND AMOUNT >= MINAMOUNT
  );
END